---
title: "面接対策"
format:
  html:
    toc: true
    number-sections: true
lang: ja
---

##	一分間で自己PRをしてください。

私の強みは、目の前の一人に寄り添い、目標達成までやり抜く情熱と責任感です。

私は、大学時代、経済的な事情などで塾などに通えない子どもたちを支援する無料塾で教室長としてボランティアを行っていました。私は、誰一人悲しい思いをさせず、経済的な格差などに影響されることなく、確かな学力をつけられる環境を作ろうという思いで、教室長として、２つの新たな試みをしました。

第一に、確かな学力をつけ、個別最適な学びのための指導の工夫です。他の大学生講師陣と議論・連携して、一人ひとりの習熟度にあったオリジナル教材を作成したり、その子にあった教え方や接し方を試行錯誤して見つけ出し、共有したりしました。その結果、生徒の学習意欲が向上し、志望校合格や成績アップへ導くことができました。

第二に、一人ひとりを尊重した環境づくりです。塾には、不登校やADHDやLDといった障害を持つ特別な支援が必要な子どもたちも多くおり、「その子が勉強に集中できるにはどうすればいいか」などを、教職課程の授業で学んだことなどを生かして、パーテーションで仕切ってみたり、講師を固定して信頼関係の構築がしやすいようにしたりなど、工夫と試行錯誤を常に続け、あたたかいまなざしで寄り添うことを意識した結果、塾が安全基地として機能し、当初は心を閉ざしていた生徒も、笑顔で通ってくれるようになりました。

この「学び続ける向上心」と、子どもたちへの情熱と責任感を武器に、貴県の教員として生徒の成長を全力で支え抜く覚悟です。

##	教員を目指した理由（きっかけ）を教えてください
私が教員を志した理由は、「生徒一人一人に寄り添い、可能性を最大限に引き出す教員の情熱」に強く心を打たれたからです。

きっかけは、中学3年生の時の経験です。私の通っていた中学校は生徒数が少なく、3年生で1クラス39人の過密状態になりました。さらに副担任の先生が産休に入られ、担任の先生が一人で全員を支えるという非常に多忙な状況でした。しかし、その先生はどれほど多忙であっても、生徒一人一人と真摯に向き合ってくれました。授業も文科省の視察が入るほど質が高く、常に私たちの成長を第一に考えておられました。

私はその先生から、教員とは単に教科を教えるだけでなく、生徒の人生に深く関わり、支えとなる「誇り高い職業」であることを学びました。私もその先生のように、どんな状況でも生徒一人一人と真摯に向き合い、その成長を全力で支えられる教員になりたいと考え、志望いたしました。

### 文科省の視察が来た授業はどんな授業？

英語の授業でした。すべてを英語で行う授業で、話の内容を、タイムラインとしてプリントに自分でまとめさせることで、全体像をつかませ、そこからとらえたことを互いに伝え合ったり、伝え合った内容を自分で再構成して、自分の意見を英語でまとめる書かせたりするなど、周りと英語で対話しながら、思考を深める言語活動を行っていました。

対話を通じて得た他者の多面的多角的な視点を踏まえ、「なぜそう思うのか」という根拠となる資料やデータを提示しながら、自分の考えを論理的に構築する力を育成しようとしている点は社会科においても非常に参考にすべきだと思うし、自分もこのような授業をしようと思います。

### 「生徒一人一人と真摯に向き合ってくれました」具体的には？

自分は数学が本当に大嫌いでした。その先生は英語の先生だったのにも関わらず、しっかり向き合って数学を教えてくれて、本当にうれしかったのを覚えています。また、その先生は、生徒一人一人のことを書くノートを作っていらっしゃいました。三者面談の時に、先生のノートをみると、びっしり書かれていて、本当に一人一人のことを見てくれているんだなと思って本当にうれしかったです。自分もそれくらい、一人一人に真摯に向き合いながら、その子の成長を全力で支えられたらと思っています。

## その県である理由
### 岐阜県の場合

私が岐阜県を志望した理由は、私を育ててくれた故郷の教育に、今度は教員として恩返しをしたいと考えたからです。

私は岐阜県の自然豊かで、生徒数の少ない小規模校で育ちました。困難な状況でも生徒のために全力を尽くす先生方の姿を見て、私も将来、岐阜の子どもたちのために汗を流せる大人になりたいと強く決意しました。



### 東京都の場合

私が、東京都の教員を志望した理由は、東京都には圧倒的な量の文化的資本があるからです。東京都は、政治・経済・文化の中枢であり、教科書で学ぶ事象が目の前に広がる『生きた教材』に溢れた街です。教員は常に学び続け、自分をアップデートしていく力が非常に重要だと思っています。多くの文化的資本を活用した充実した授業ができる環境が整っている点が魅力的で、東京都を志望しました。


## 中学校である理由

私が、中学校の教員を志望する理由は、中学生は一番難しい時期で、だからこそ教員の支える力がとても重要であると考えているからです。

中学生は、自己肯定感が揺らぎやすく、人間関係や将来に対して大きな不安を抱える「最も多感で難しい時期」です。私自身、中学3年生の時に1クラス39人という過密な環境で、担任の先生が私たち一人一人に寄り添ってくださった経験から、この時期の教員の関わりがいかに生徒の支えになるかを肌で感じてきました。（志望動機とつながり）

自分も、学習指導と心のケアの両面から生徒の伴走者として寄り添い、子どもたちがのびのびと成長する支えになりたいと考え、中学校の教員を志望しています。

## 社会科を志望した理由

私が、社会科教員になろうと思ったのは、社会の仕組みや社会的事象を学ぶことによって、この世界の見方や考え方が変わる楽しさを生徒に伝えたいと考えているからです。

私は、移動中の車窓から外の風景を眺めるのが大好きなのですが、そこには自分の知らない世界が無限に広がっています。例えば、街中で「証券」という看板を目にしたとき、単なる文字として通り過ぎるのではなく、「証券とは何か？」「なぜここにこの会社があるのか？」と問いを立てることで、そこから経済や社会の繋がりを紐解いていくことができます。

自ら調べ、知識を得ることで、それまでただの「景色」だったものが、意味を持った「社会の営み」へと変わっていくこのワクワク感こそが、社会科を学ぶ最大の醍醐味だと感じています。

私の授業を通して、生徒が学校の外に出たときに「あ、これは授業でやったあのことだ！」と発見し、自ら探究し続けられるようなきっかけを作りたいと考えています。

### 具体的に、自ら探究し続けられるようなきっかけを作る授業とはどんな授業ですか？

自ら探究し続けられるようなきっかけを作る授業は、日常生活の疑問とつなげた課題を提示し、その解決のために様々な資料を用意し、生徒自らその資料同士の関連などに気づき、解決していく授業です。その最後に、日常に通じる発展的な疑問などを提示することで、自ら勉強するようなインセンティブをつくることができます。

## 趣味は？

自分の趣味は、地域のグルメを開拓することです。
私は、現在は高知県の大学に通っています。全く知らない土地だったので、全力でその地を楽しもうと、休日にいろんなところへ出かけ、おいしい店などを見つけていました。その店の人などと仲良くなったりして、いろいろお話をすることで、さらに情報が手に入ります。このようにお店を開拓しながら、そこのお店やそこの常連さんなどと沢山会話することで、地域のことをよく知れるだけでなく、自分のストレス発散になります。


::: {.callout-note collapse="true"}
# 趣味を聞く理由

趣味は労働問題が深刻化している中で、不祥事になるような趣味を持っていないか、ストレスのはけ口があるか、などを見ていると思われる。そのため、ストレスはこのように発散していることを伝えることが必要だ。

:::


## 長所と短所を教えてください
### 長所

論　私の長所は、やると決めたことは、強い熱意と責任感をもってやりきることができることです。

例　自分は、経済的な事情などで塾に通えない子どもたちへ、学習支援を行うボランティアの塾活動で教室長を務めていました。土曜夜に行われていましたが、自分は土曜だけでなく、平日なども活用していろんな一人一人に合った教材などをつくったり、その子の成績を上げるためにはどうすればよいかを真剣に考え、２～３時間仲間たちと議論をしたりしていました。

策　このように、私は、子どもたちのために、常に努力を怠らず、強い熱意と責任感を持って、その仕事を全うすることができます。

### 短所

策　私の短所は、一つのことに没頭しすぎてしまう傾向があり、目の前の課題に深く集中するあまり、他のことが後回しになってしまうことです。特に教材研究など、納得がいくまで追求したくなります。

例＆策　無料塾ボランティアの時、いろんなことを同時に進めていく中で、この短所を自覚し、付箋を用いて、優先順位などを決めてタスクをこなしていくことで、この短所を乗り越えようと努力してきました。
教員は、複数の児童生徒を相手に、複数の仕事を同時進行で進めていく必要があることを理解しています。この短所は、熱心さという長所として生かせるように努力していきます。

## 周りからどんな人と言われる？

明るくて親しみやすいけれど、やるべきことにすごく熱中する人とよく言われます。
友人たちの間ではいじられ役に回ることが多く、場を和ませるタイプなのですが、一方で教育ボランティアなどの活動では、納得がいくまで頑張るため『そこまでやるのか』と驚かれることも多いです。

## 理想の教師像とは

論 私が考える理想の教師像は、一人一人にやさしく寄り添い、教育に対する熱意と使命感を持って、子どもたちのために常に努力をし続ける教員です。

例　自分は、経済的な事情などで塾に通えない子どもたちへ、学習支援を行う塾で教室長を務めていました。土曜夜に行われていましたが、自分は土曜だけでなく、平日なども活用していろんな一人一人に合った教材などをつくったり、その子の成績を上げるためにはどうすればよいかを真剣に考え、２～３時間仲間たちと議論をしたりしていました。（長所と同エピ）

策　子どもたちのために、強い使命感を持って、全力で取り組むことができる教員は、保護者やこどもたちからも信頼を獲得し、さらに子どもたちへ努力を注ぎ続ける環境づくりにもつながるとも思っています。このような教員になれるように常に努力をし続けていきたいと思います。

## 目指す学級像
論　仲間と共に支え合い、高め合い、学級づくりを目指します。

例　私が小・中学生のころ、みんながともに支え合い、高め合うことができる学級でした。困っているような子どもがいたら、周りの子が気付いて声を掛けたり、助けを求めたりして、とてもあたたかい学級になっていました。その環境は、みんな過ごしやすく感じていて、私もとても楽しかったのを覚えています。

策　そのために、自分も生徒の良かった点があれば、その日のうちに生徒に伝えたり、生徒同士で良いところを伝えあったりする活動を積極的にしたいと思います。自分が目指す学級経営ができるように先輩教員の先生方のお力もお借りしながら、頑張っていきたいと思います。

## 挫折経験や失敗経験を教えてください


::: {.callout-caution collapse="true"}
# 挫折経験いま思いつかないからあとで。

書いていい挫折経験がない笑
:::

論　挫折経験は、

例 

## あなたがやってみたい授業は？具体的に？
ICT組み込むと良い　地域連携などの要素も面白いかも
私がやってみたい授業は、

## ICTを使うメリット・デメリットは何か
ICTを使うメリットは、ICTによって、資料の提示などが非常に簡単になるほか、視覚的にみせられるので、理解がしやすくなる利点があります。例えば、社会科では、地図の授業で、True Size of というメルカトル図法でどれくらい実際の面積や形とずれがあるかを見れるサイトがあります。生徒自身が、視覚的に触れる点が大きな利点かなと思います。

一方、デメリットとして、「ICTを用いること」が目的になるという状況に陥ってしまうことです。あくまでツールであるので、そこに陥らないよう気を付けなければいけないと思います。ICTを用いる目的をはっきりさせて、しっかり使う時間と使わない時間のメリハリをつけて、うまく活用していきたいと思います。

## 担任を持った際に最初に生徒に伝えたいこと
論　私は、夢や目標を立て、あきらめないで努力し続けることの大切さを伝えたいと思います。

例　私の中学時代の友人は、子どものころから自動車が大好きで、自動車整備士の夢を持っていました。夢をかなえるために、彼は必死に勉強し、自動車科のある高校と、自動車整備の専門学校を卒業し、今は名古屋のディーラーで働いています。夢に向かって頑張っている必死に勉強に励む彼の瞳はとても輝いていたと記憶しています。

策　子どもは何にでもなれる可能性を秘めた存在です。夢や目標をたて、それに向かってあきらめないで努力し続けることは、自分の能力を切り開くきっかけとなれるし、もしそれが叶わなくても、その経験が、みんながいずれ必要となる「未来を自分で切り開く力」へ変わります。私は、彼のように、夢や目標を立て、あきらめないで努力し続けられるような人になってほしいと思います。

## 地元の魅力を教えてください。
岐阜県の魅力は、平野部のアクセスの容易さと多様な自然環境が作り出す文化です。平野部は名古屋への通勤圏として大きく発展しており、ほかの都市圏への移動なども容易です。この容易さは、様々な文化的事象の流入を生んでおり、全国的に見て新しいものが入ってきやすいため、非常に住みやすい環境になっています。
一方で、飛騨地方は山間部であまり文化的な流入が少ないためか、独自の文化や歴史をたどっており、これがまた魅力の一つです。下呂温泉や白川郷などの観光地は大人気で、いま高山は外国人観光客に非常に注目されています。この自然環境に強く影響された多様な文化が岐阜の誇れる魅力の一つだと自分は思っています。


## 交友関係で苦労したことはある？
論 交友関係で苦労したことは、




## あなたが考える良い授業とは？
論 私の考える良い授業とは、物事の疑問を生徒自身で見つけ、対話や発言が積極的にして、ある程度の結論が見出せる授業が良いと思う。生徒が最終的に「学ぶ」という行為が、自らの興味と意志で主体的にできる授業




## これからの時代の教師に求められる資質能力は何だと思うか。

## あなたの教育観を教えてください
（教育観：子ども観＋学習観＋指導観）

論　私は、子どもたちを「自分の力で無限の可能性を引き出せる存在」として捉え、あくまで伴走者として子どもたちを支え、子どもたちが自ら発見し、主体的に学んでいくような教育をしたいと考えています。

例 


## 理想の教師像とは
論　私の理想の教師像は、強い責任感と使命感を持って、常に学び続けると同時に、子どもたちにあたたかく寄り添う教師です。

例　私の中三の社会科の先生は、特に授業を工夫して行っていました。資料をたくさん持ってきて、資料同士をつなげさせることを意識させながら、気づいてきたことをまとめさせる方法をとっていました。これまで、一方的な授業ばかりで、あまりそういう授業を受けてこなかった自分は、この授業に衝撃を受け、同時に社会科がとても面白くなりましたし、私が社会科教員を目指す一つのきっかけとなっています。また、その先生は、同時に子どもたちに寄り添い、受験や人間関係など、自分の悩みにずっと寄り添ってくれました。

策　私は、授業力向上のため、大学の先生と積極的にお話して、自分でどのアプローチで生徒が興味を持ち、かつ最も能力がつけられるかを、常にいろんな書籍などで研究し、指導法等の授業で実践するなど取り組んできました。また、（SUJ活動において）子どもたちの話を傾聴し、寄り添えるように努力を続けてきました。この経験が教員になって生かせると考えています。

## 信頼される教師はどんな教師？
論　私が思う信頼できる教師は、すべての生徒を誰一人取り残さず把握しつつ、生徒が気軽に相談ができるような教師です。

例　子どもたちと積極的に関わることで、子どもたちへ気軽に相談できる教師であると見せることで、子どもたちのSOSや変化の様子を見逃さない。


## 近年、教師のモラル低下についてどう思うか
論　教師のモラル低下は、教師の名誉を傷つけ、子どもたちや国民からの信頼を失うことで、非常に問題であると思います。

例　（岐阜）例えば、近年岐阜県では、生徒を盗撮したり、性的羞恥心を害するメッセージを送信したりなどして免職された教師がいました。決して許されないことです。

策 子どもたちを守るため、もし同僚がそういうことをしていたら止め、すぐに上長に報告します。教師として高い倫理観と、「教育」という国の根幹をなす崇高な使命を受け持つ責任感と使命感で校務に取り組んでまいります。

## 教師には様々な研修の機会が多く設けてあるが、どう思う？
論 私はとてもありがたいことだと思うし、私も積極的に参加したいと思います。

例 変化の激しい社会の中で、社会から求められる姿や子どもたちの様子は変化していきます。私も、先述の塾活動で、なかなか対応に苦慮している児童生徒には、その中で、教員は、常に学び続け、アップデートし続けていくことが必要だと思います。

## 最近の気になるニュースは？
最近の気になるニュースは、デジタル教科書が国定教科書として使用できることです。
文字を大きくしたり、動画の教材を使えたりなど、活用の幅が非常に広がり、多様化する児童生徒に合わせた工夫ができるので、素晴らしいことだなと思います。ただ、紙の方が学習の定着率が高いという話があるので、ミックスして効果的に使っていくことが、大切だと思います。


## 苦手な人のタイプは？
論　私は、共通の目標に対して『目的意識の共有が十分にできていない方』との接し方に難しさを感じることがあります。全員が同じ熱量で取り組めない状況は、組織全体の士気や、一部のメンバーへの負担増加に繋がると考えているからです。

例　私は大学時代によさこいサークルで、インストラクターとして取り組んでいました。みんなの前で手本として見せる必要性があったので、自分は夜遅くまで必死に練習していたのですが、どうしても熱意の差があるせいで、チームがまとまらず崩壊してしまったことがあります。

策　その時の経験から、苦手だと避けるのではなく、まずは『なぜこの活動が必要なのか』という目的を丁寧に共有すること、そして相手の得意な役割をお願いして当事者意識を持ってもらうことを意識しています。苦手な方からも学ぶことも多いですので、「子どもたちのために」協力する姿勢が大切だと思っています。チーム学校の一員として、周囲と歩調を合わせる働きかけを大切にしたいと考えています。


::: {.callout-important}
そう言う人であっても話を聞く！
苦手意識があっても、「子どもたちのために」協力する姿勢が大切
:::

## 保護者が学校に求めることは何だと思いますか。
保護者が学校に求めることは、学校生活を通じて、学力も含めて、子どもが自立して生きていける力を身に着けることだと思います。そのために、私は、

## 社会科が苦手な子どもたちには、どのように対応しますか
私自身、社会科が苦手だったことがなかったので、周りのいろんな人に原因を聞いてみたことがあります。そのとき、「暗記が苦手だから」というのが多かったです。私は、社会科は全部が全部暗記ではないと思っています。ストーリーとして背景などを知り、知識を関連付けることで、より構造的な見方ができるようになり、物事の見方に深みが増すことが、一番面白く、かつ覚えやすい手法だと思います。教えるときは、背景などを織り交ぜて、ストーリーとして構築するなど、横断的な視点で見ていく教え方をして、苦手な子でも覚えやすいような授業を目指したいと思います。











---

[面接対策](/Kyousai/index.qmd)へ戻る