---
title: "解説は生徒の思考を奪う"
format: 
  html: 
    toc: true
    number-sections: true
lang: ja
---
## 解説の有効性

授業において、資料の解説などを行うことも多いと思う。解説は、生徒の理解を助けることはもちろんのこと、解説の内容によっては、生徒の興味を引きだし、関心を高めることにつながる。

教員としても、知っていることは生徒に伝えたいという気持ちがあると思う。特に、教材研究をきっちりとされている先生ほど、いろんなことを知っているので、ついつい生徒に話したくて、解説してしまうことも多いであろう。

社会科教員は、もはや性といってよいほどその症状が現れる。

## 解説の問題点

このような状況を継続すると...

* 学力高位層やその教科に興味のある子どもには解説の効果があるが、学力低位層やその教科に興味がない子どもには、退屈で言葉が耳を通り抜けるだけの時間になり、クラス内の学力格差が開く。
* 生徒から出てもおかしくないような意見を教員が解説で奪ってしまい、生徒から引き出せたはずの学びをつぶしてしまう。
* 生徒が、どんな意見でも先生が解説してくれるという安心感から、あまり主体的に考えず、テキトーな意見を出し始める。

難しい言葉や誰一人として生徒がわかっていないような言葉を解説することは決して間違っている行為ではない。しかし、同時に**生徒の思考を奪ってはいないかというのは、常に念頭に置いて授業を行っていくことが大切**である。


::: {.callout-important}

**授業の主役は教師ではなく生徒**である。このことは決して忘れてはならないと思う。

教師が話し続ける授業は、教師の満足感は高いうえ、とても楽な授業だと思う。しかし、それは生徒が育つ機会を失わせてしまう。**知識だけではない**という学校の意義をよく考えよう。
:::

## 解決法の一例

解決の方法として一例を示す。ただし、筆者の専門は社会科であるため、社会科の授業での取り組みを示す。他の教科でも応用ができるであろう。

>（中学地理の授業にて）
>
>生徒「経済特区を作っていたんだと思います。」
>
>教師「みんな意味わかった？経済特区というワードが出てきましたね。誰か経済特区というワードの意味を説明してほしいな（誰か生徒のなかで説明する人を当てる）」

これは生徒に説明させる例である。教員が経済特区を説明してしまっても構わないが、既に読み取っている生徒もいるであろう。生徒に説明させることで、その生徒の表現力を高めると共に、自己肯定感も高める。

---

[トップページに戻る](https://yamachan050125.github.io/Kyouiku-gaku/)